### ISSUE TITLE
LL1971-2Variant Assess

### ISSUE THREAD

**Issue by pnrobinson** [HL7/phenomics-exchange-ig#79]
I am getting an error message from the FHIR server that 
Resource/LL1971-2/ cannot be found.
This LOINC code is an 'answer' for  [LOINC:69548-6  Genetic variant assessment](https://loinc.org/69548-6) 	

@khalifa-aly do we need to add this code somewhere to the PhenotypeVariant message?

**Comment by ShahimEssaid** [comment]
This was a terminology server issue where the LOINC value sets were not available.  Closing.
